//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGENCOMPANIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TGENCOMPANIA()
        {
            this.TSEGPOLITICA = new HashSet<TSEGPOLITICA>();
            this.TSEGUSUARIO = new HashSet<TSEGUSUARIO>();
        }
    
        public decimal CCOMPANIA { get; set; }
        public Nullable<decimal> OPTLOCK { get; set; }
        public string NOMBRECOMPANIA { get; set; }
        public string ESLOGANCLIENTE { get; set; }
        public string ESLOGANCORE { get; set; }
        public string NOMBRECORTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSEGPOLITICA> TSEGPOLITICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSEGUSUARIO> TSEGUSUARIO { get; set; }
    }
}
