//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSEGROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSEGROL()
        {
            this.TSEGUSUARIOROL = new HashSet<TSEGUSUARIOROL>();
        }
    
        public decimal CROL { get; set; }
        public decimal CCOMPANIA { get; set; }
        public string CCANAL { get; set; }
        public Nullable<decimal> OPTLOCK { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> ACTIVO { get; set; }
        public string ICONO { get; set; }
        public string COLOR { get; set; }
    
        public virtual TGENCANALES TGENCANALES { get; set; }
        public virtual TGENCOMPANIA TGENCOMPANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSEGUSUARIOROL> TSEGUSUARIOROL { get; set; }
    }
}
