//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSEGUSUARIOSESSIONHISTORIA
    {
        public string CUSUARIO { get; set; }
        public decimal CCOMPANIA { get; set; }
        public System.DateTime FCREACION { get; set; }
        public Nullable<decimal> NUMEROINTENTOS { get; set; }
        public string IDSESSION { get; set; }
        public Nullable<System.DateTime> FINICIO { get; set; }
        public Nullable<System.DateTime> FSALIDA { get; set; }
        public string ACTIVO { get; set; }
        public Nullable<decimal> TIEMPOSESION { get; set; }
        public Nullable<System.DateTime> FULTIMAACCION { get; set; }
        public string CESTADO { get; set; }
        public string USERAGENT { get; set; }
        public string CTERMINALREMOTO { get; set; }
    }
}
